application: octahedronstatus
version: 1
runtime: python
api_version: 1

handlers:
- url: /.*
  script: handlers.py
  
admin_console:
 pages:
 - name: Add Application
   url: /register

